### ISSUE TITLE
Is a 2.6.5 release planned?

### ISSUE THREAD

**Issue by wilkinsona** [FasterXML/jackson-datatype-jdk7#6]
Apologies for using an issue to ask this question. Please let me know if there's a more appropriate way to do so in the future.

Is there a 2.6.5 release planned for this module alongside the other projects that were tagged and released a few days ago? I am asking as Spring Boot provides dependency management for many Jackson modules using the same version. We've upgraded to 2.6.5 and I just noticed that jackson-datatype-jdk7:2.6.5 will not resolve.

**Comment by cowtowncoder** [comment]
Thank you for reporting this -- lack of released version was my mistake, and I will proceed to cut a release now. Intention is to keep that up to date with 2.6.x patch release process. I missed it because I had locally moved it to another location, as it is being deprecated for 2.7.

**Comment by cowtowncoder** [comment]
Release should now be on its way to Maven Central. Thank you for reporting this.

**Comment by wilkinsona** [comment]
Thank you, @cowtowncoder. Much appreciated.
